[package]
name = "mca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
fastanvil = "0.26.0"
fastnbt = "2.3.2"
flate2 = "1.0.25"
